import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/nav/Navbar";
import MainLayout from "@/layout/MainLayout";

const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "next-themes";
import { AnimatePresence } from "framer-motion";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <ThemeProvider attribute="class" defaultTheme="light">
        <MainLayout>
          <AnimatePresence mode="wait" initial={false}>
<Navbar /> <body className={inter.className}>
        {children}</body>
          </AnimatePresence>
        </MainLayout>
      </ThemeProvider>
        
    </html>
  );
}
